builds:
- id: ocm-transport-plugin
  main: ./cmd/transport-controller
  binary: ocm-transport-plugin
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64

kos:           
  - repository: ghcr.io/kubestellar/ocm-transport-plugin/transport-controller
    main: ./cmd/transport-controller
    build: ocm-transport-plugin
    tags:
    - '{{.Version}}'
    - latest
    bare: true
    preserve_import_paths: false
    ldflags:
    - "{{ .Env.LDFLAGS }}"
    platforms:
    - linux/amd64
    - linux/arm64
    env:
    - CGO_ENABLED=0
release:
  draft: false
  prerelease: auto
  mode: keep-existing


